title: TI10KO
author: Maksym Titenko
email: titenko.m@gmail.com
description: >
  This is a demo page for minima-reboot, a bootstrap-based rewrite of Jekyll's
  default minima theme. It is simple, lightweight, and responsive.
  You can use it with your GitHub Pages site by adding the line
  "theme: aterenin/minima-reboot" to _config.yml.

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- posts.md
- github.md

footer_icons:
  url: https://titenko.github.io/
  baseurl: https://titenko.github.io/site/
  icon: icon-github.svg

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: barryclark/jekyll-now
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: jekyllrb
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
